/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.79
 * Generated at: 2023-08-24 11:48:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Main</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/index.css\">\r\n");
      out.write("    <link rel=\"icon\" href=\"img/로고.png\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../header/header.css\"/>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("            <div class=\"header_full_box\">\r\n");
      out.write("            <div class=\"header_nav\"><a href=\"main.html\"><img src=\"img/로고.png\" width=\"100px\" height=\"40px\"></a></div>\r\n");
      out.write("            <div class=\"header_nav\"><a href=\"/ljm/gymList.html\">운동시설</a></div>\r\n");
      out.write("            <div class=\"header_nav\"><a href=\"/pmg/myPage.html\">마이페이지</a></div>\r\n");
      out.write("            <div class=\"header_nav\"><a href=\"/nyc/announcement .html\">공지사항</a></div>\r\n");
      out.write("            <div class=\"header_nav\"><a href=\"/nyc/FAQ.html\">FAQ</a></div>\r\n");
      out.write("            <div class=\"header_nav\"><a href=\"/ljm/search.html\"><input type=\"text\" placeholder=\" 운동시설 검색\"></a></div>\r\n");
      out.write("            <div class=\"header_nav\"><a href=\"/pmg/login.html\">로그인</a></div>\r\n");
      out.write("            <div class=\"header_nav\"><a href=\"/pmg/joinAgree.html\">회원가입</a></div>\r\n");
      out.write("        </div><!--header-->\r\n");
      out.write("    <div id=\"full_box\"><!--전체 총 div-->\r\n");
      out.write("        <div class=\"main_banner\"><!--banner-->\r\n");
      out.write("            <div class=\"slides-wrap\">\r\n");
      out.write("                <ul class=\"slide-box\">\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <div class=\"slide-img\" id=\"img1\"></div>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <div class=\"slide-img\" id=\"img2\"></div>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <div class=\"slide-img\" id=\"img3\"></div>\r\n");
      out.write("                  </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <!-- &lt, &gt는 html에서 < , > 를 나타낼때 사용 -->\r\n");
      out.write("                <div class=\"prev\">&lt</div>\r\n");
      out.write("                <div class=\"next\">&gt</div>\r\n");
      out.write("              </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <a href=\"/ljm/search.html\"><div class=\"input_div\"><!--search-->\r\n");
      out.write("           <input type=\"text\" placeholder=\"어떤 운동을 찾고 계신가요?\">\r\n");
      out.write("            <div class=\"search_img\">\r\n");
      out.write("                <img src=\"https://cdn-icons-png.flaticon.com/512/2866/2866321.png\" width=\"30px\" >\r\n");
      out.write("            </div>\r\n");
      out.write("        </div><!--search--></a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        <!--Main-->\r\n");
      out.write("        <div class=\"main_full\"><!--main div1-->\r\n");
      out.write("            <a href=\"/ljm/gymList.html\">\r\n");
      out.write("              <div class=\"main1\">\r\n");
      out.write("              <span class=\"m\">내주변 운동시설</span>\r\n");
      out.write("              </div>\r\n");
      out.write("             </a>\r\n");
      out.write("\r\n");
      out.write("            <a href=\"/cuj/place.html\">\r\n");
      out.write("                <div class=\"main2\"><!--main div2-->\r\n");
      out.write("                <span class=\"m\">지도에서 찾아보기</span>\r\n");
      out.write("                </div>\r\n");
      out.write("             </a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"under_icon_full\"><!--under icon-->\r\n");
      out.write("            <div class=\"under_icon\">\r\n");
      out.write("               <a href=\"https://blog.naver.com/cdwcgw1/223190257403\" target=\"_blank\"><img src=\"img/mainImg/러닝 이미지.png\"></a> \r\n");
      out.write("                러닝 \r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"under_icon\">\r\n");
      out.write("               <a href=\"https://blog.naver.com/cdwcgw1/223190260857\" target=\"_blank\"><img src=\"img/mainImg/스트레칭 아이콘.jpg\"></a> \r\n");
      out.write("                스트레칭 \r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"under_icon\">\r\n");
      out.write("                <a href=\"https://blog.naver.com/cdwcgw1/223190259995\" target=\"_blank\"><img src=\"img/mainImg/운동아이콘.jpg\"></a>\r\n");
      out.write("                바벨 \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <br>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"long_img\"><!--남색 긴 사진-->\r\n");
      out.write("            \r\n");
      out.write("            <h2>간단해요! 흔들리면 그건 지방이에요!</h2>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"video\">\r\n");
      out.write("            <iframe width=100% height=\"400px\" src=\"https://www.youtube.com/embed/5eMhsNZ2N58\" title=\"YouTube video player\" frameborder=\"0\"></iframe> \r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"footer_full_div\"><!--footer-->\r\n");
      out.write("            <div class=\"footer1\"> <!--footer div1-->\r\n");
      out.write("                <div>\r\n");
      out.write("                    <img src=\"img/로고.png\" style=\"margin-bottom: 10px;\"></div>\r\n");
      out.write("                <div class=\"name\">살빼조</div>\r\n");
      out.write("                <div>서울특별시 노원구 상계로1길 </div>\r\n");
      out.write("                <div>장민지|이종민|최욱진|나윤찬|박민규</div>\r\n");
      out.write("                <div>이메일 : bbagym@gmail.com | 사업 및 제휴문의 : bbagym@gmail.com</div>\r\n");
      out.write("                <div class=\"personal\"><a href=\"../ljm/privacyPolicy.html\">개인정보 처리 방침</div></a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"footer2\"><!--footer div2-->\r\n");
      out.write("                <div class=\"sns\">\r\n");
      out.write("                    <a href=\"https://blog.naver.com/PostList.naver?blogId=cdwcgw1\" target=\"_blank\">\r\n");
      out.write("                        <img src=\"img/mainImg/네이버블로그.png\" width=\"32\" height=\"32\">\r\n");
      out.write("                    </a>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"sns\">\r\n");
      out.write("                    <a href=\"https://www.instagram.com/dagym_app\" target=\"_blank\">\r\n");
      out.write("                        <img src=\"img/mainImg/인스타.png\" width=\"32\" height=\"32\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"sns\">\r\n");
      out.write("                    <a href=\"https://www.facebook.com/dagym0101\" target=\"_blank\">\r\n");
      out.write("                        <img src=\"img/mainImg/페이스북.png\" width=\"32\" height=\"32\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div><!--footer 끝-->\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.0.js\" integrity=\"sha256-JlqSTELeR4TLqP0OG9dxM7yDPqX1ox/HfgiSLBj8+kM=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"js/index.js\"></script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
