/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.79
 * Generated at: 2023-08-24 10:16:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class faq_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/faq.css\">\r\n");
      out.write("    <link rel=\"icon\" href=\"../img/로고.png\">\r\n");
      out.write("    <title>FAQ page</title>\r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("        \r\n");
      out.write("            \r\n");
      out.write("<div class=\"q-div\">\r\n");
      out.write("    <br>\r\n");
      out.write("<h3>Q. 빠짐은 어떤 서비스인가요?</h3>\r\n");
      out.write("\r\n");
      out.write("<div class=\"a-div\">\r\n");
      out.write("A.  빠짐은 운동시설 정보를 알고 싶을 때, 원하는 운동시설의 정보를 간편하게 얻고 불편한 상담 없이 터치 몇 번으로 바로 결제까지 할 수 있는 서비스입니다.<br>\r\n");
      out.write("\r\n");
      out.write("    또한 여러 지역이나 종목의 운동시설을 <b>최대 3개</b> 까지 골라 함께\r\n");
      out.write("    결제하면 약 <b>80% 할인된 가격</b> 으로 \r\n");
      out.write("    이용할 수 있는 빠짐만의 통합 회원권 서비스도 제공하고 있습니다.\r\n");
      out.write("    <br>\r\n");
      out.write("\r\n");
      out.write("    다니고 싶은 운동시설의 가격 및 시설 사진을 참고해 비교하시고, \r\n");
      out.write("    빠짐에서 언제나 최저가로 더 편하게 운동 다니세요!\r\n");
      out.write("</div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"q-div\">\r\n");
      out.write("<h3>Q. 빠짐 회원가가 무엇인가요?</h3>\r\n");
      out.write("\r\n");
      out.write("<div class=\"a-div\">\r\n");
      out.write("A.  빠짐과 운동시설간의 제휴로 빠짐 회원 분들께만 \r\n");
      out.write("    <b>특별하게 제공해드리는 할인가</b>입니다.\r\n");
      out.write("    <br> \r\n");
      out.write("    빠짐 앱에서 결제하시면 바로 회원가 적용을 받으실 수 있습니다.\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"q-div\">\r\n");
      out.write("<h3>Q. 단일회원권이란 무엇인가요?</h3>\r\n");
      out.write("\r\n");
      out.write("<div class=\"a-div\">\r\n");
      out.write("A.  기존 운동시설을 다니던 그 방식 그대로 빠짐을 통해 1개 시설을03\r\n");
      out.write("    결제하여 등록할 수 있는 회원권입니다. \r\n");
      out.write("    <br>\r\n");
      out.write("    방문하여 결제했을 때와 \r\n");
      out.write("    동일하게 이용하실 수 있습니다. \r\n");
      out.write("    <br>\r\n");
      out.write("    빠짐을 통해 결제하시면 \r\n");
      out.write("    <b>빠짐회원가 할인과 무이자 할부 혜택</b> 까지 받으실 수 있으니, \r\n");
      out.write("    <br>\r\n");
      out.write("    마음에 드는 시설이 있다면 빠짐으로 편리하게 바로 결제해보세요!\r\n");
      out.write("    <div class=\"a-div\">\r\n");
      out.write("*다만, 출석 시 지급받는 포인트 및 쿠폰은 사용이 불가합니다.\r\n");
      out.write("<br>\r\n");
      out.write("*통합회원권에서만 출석 시 포인트 지급 및 쿠폰 사용 가능\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"q-div\">\r\n");
      out.write("<h3>Q. 통합회원권(다른 곳 같이다니기)란 무엇인가요?</h3>\r\n");
      out.write("\r\n");
      out.write("<div class=\"a-div\">\r\n");
      out.write("A.  위치와 종목에 상관없이 내가 다니고 싶은 운동시설을 <b>최대 3개</b>까지 \r\n");
      out.write("    골라 <b>80% 할인</b>받아 다니는 빠짐만의 특별한 서비스 입니다.\r\n");
      out.write("    <br>\r\n");
      out.write("    기존 회원권과 동일하게 1, 3, 6, 12개월 모두 이용이 가능하며\r\n");
      out.write("    빠짐에 등록된 운동시설 중 어느 곳이든 \r\n");
      out.write("    빠짐 통합회원권으로 조합을 만들어보세요! \r\n");
      out.write("    <br>\r\n");
      out.write("    결합하는 센터의 조합에 따라 가격이 다르게 책정되며\r\n");
      out.write("    <b>최대 80%</b>까지 할인 됩니다.\r\n");
      out.write("</div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"q-div\">\r\n");
      out.write("<h3>Q. 결제 당일부터 운동을 시작해야하나요?</h3>\r\n");
      out.write("\r\n");
      out.write("<div class=\"a-div\">\r\n");
      out.write("A.  아님니다 결제 시 운동시작일을 <b>최대 2주 뒤</b>까지 \r\n");
      out.write("    원하는 날짜로 고를 수 있습니다.\r\n");
      out.write("    <br> \r\n");
      out.write("    아무 때나 편리하게 결제하신 뒤, \r\n");
      out.write("    원하시는 날짜부터 운동을 시작하세요!\r\n");
      out.write("</div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"q-div\">\r\n");
      out.write("<h3>Q. 운동시작일을 변경하고 싶습니다.</h3>\r\n");
      out.write("\r\n");
      out.write("<div class=\"a-div\">\r\n");
      out.write("A.  다음 기준에 맞게 기존 운동시작일로부터\r\n");
      out.write("    <b>주 이내, 최초 1</b>회에 한하여 변경해 드립니다.\r\n");
      out.write("    <br>\r\n");
      out.write("\r\n");
      out.write("    기존 운동시작일 이전인 경우\r\n");
      out.write("    <br>\r\n");
      out.write("    -> 즉시 변경이 가능합니다.\r\n");
      out.write("    <br>\r\n");
      out.write("    <br>\r\n");
      out.write("    기존 운동시작일 이후이나,\r\n");
      out.write("    사정상 시설에 1회도 방문하지 않은 경우\r\n");
      out.write("    <br>\r\n");
      out.write("    -> 운동시설과 논의가 필요하며, \r\n");
      out.write("    경우에 따라서 변경이 불가능할 수도 있습니다.\r\n");
      out.write("    <br>\r\n");
      out.write("    <br>\r\n");
      out.write("    이미 운동을 시작한 경우\r\n");
      out.write("    <br>\r\n");
      out.write("    -> 변경이 불가능합니다. \r\n");
      out.write("    <br><br>\r\n");
      out.write("    다만, 단일회원권 고객님의 경우 \r\n");
      out.write("    운동시설에 직접 문의하여 홀딩을 신청하거나,\r\n");
      out.write("    <br> \r\n");
      out.write("    3개월 이상의 통합회원권 고객님의 경우 \r\n");
      out.write("    빠짐 웹 내 홀딩기능을 이용할 수 있습니다.\r\n");
      out.write("</div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"q-div\">\r\n");
      out.write("<h3>Q. 통합회원권으로 다니던 시설을 변경하고 싶습니다.</h3>\r\n");
      out.write("\r\n");
      out.write("<div class=\"a-div\">\r\n");
      out.write("A.  원칙적으로 결제한 운동시설의 조합은 등록기간 동안 \r\n");
      out.write("    <b>변경하실 수 없습니다.</b> \r\n");
      out.write("    <br>\r\n");
      out.write("    다만, 이용 중인 제휴시설의 폐업 등의 \r\n");
      out.write("    이유로 일부 시설 이용이 불가능한 경우 \r\n");
      out.write("    고객센터에서 변경 또는 추가를 도와드립니다.\r\n");
      out.write("</div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"q-div\">\r\n");
      out.write("<h3>Q. 회원권 기간 일시 정지(홀딩)이 가능한가요?</h3>\r\n");
      out.write("\r\n");
      out.write("<div class=\"a-div\">\r\n");
      out.write("A.  홀딩은 (통합회원권)의 경우에만 내일 이후 부터 운동 종료일까지 \r\n");
      out.write("    <b>웹 내 [나의 회원권] -> [기간 정지(홀딩) 신청]</b> 에서 \r\n");
      out.write("    가능합니다! \r\n");
      out.write("    <br>\r\n");
      out.write("    홀딩을 신청 하신 후, 회원권을 다시 시작하고 싶으시다면\r\n");
      out.write("    홀딩 화면에서 <b>[다시 시작하기]</b> 버튼을 클릭!\r\n");
      out.write("    <br>\r\n");
      out.write("    클릭한 순간부터 바로 이용 가능합니다.\r\n");
      out.write("</div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"q-div\">\r\n");
      out.write("<h3>Q. 홀딩은 며칠동안 가능한가요?</h3>\r\n");
      out.write("\r\n");
      out.write("<div class=\"a-div\">\r\n");
      out.write("A.  회원권 기간이 3개월인 경우 \r\n");
      out.write("    2주 1회, 6개월 4주 3회, 12개월 8주 6회 제공되고 있습니다.\r\n");
      out.write("</div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"q-div\">\r\n");
      out.write("<h3>Q. 다니던 시설이 폐업했을 땐 어떻게 해야하나요?</h3>\r\n");
      out.write("\r\n");
      out.write("<div class=\"a-div\">\r\n");
      out.write("A.  빠짐은 고객님께서 편리하고 안전하게 운동하실 수 있도록 \r\n");
      out.write("    최선을 다하고 있습니다.\r\n");
      out.write("    <br>\r\n");
      out.write("[통합회원권]\r\n");
      out.write("<br><br>\r\n");
      out.write("1) 환불을 원하시는 경우\r\n");
      out.write("<br><br>\r\n");
      out.write("    -> 문제가 발생한 시설 요금만 부분취소를 받으시거나, \r\n");
      out.write("    전체 결제 취소 모두 가능합니다.\r\n");
      out.write("    <br> \r\n");
      out.write("    이 경우 그동안\r\n");
      out.write("    이용한 기간에 해당하는 금액만큼만 공제하고 \r\n");
      out.write("    별도의 위약금(10%)없이 환불해 드립니다.\r\n");
      out.write("    <br><br>\r\n");
      out.write("2) 환불을 원하지 않는 경우\r\n");
      out.write("<br><br>\r\n");
      out.write("    -> 빠짐 제휴시설 내 다른 운동시설로 변경해드립니다.\r\n");
      out.write("    <br><br>\r\n");
      out.write("[단일회원권]\r\n");
      out.write("<br><br>\r\n");
      out.write("1) 결제일로부터 7일 이전\r\n");
      out.write("    -> 이용기간에 관계없이 100% 현금으로 환불이 가능합니다.\r\n");
      out.write("    <br><br>\r\n");
      out.write("2) 결제일로부터 8일 이후\r\n");
      out.write("    -> 운동시설과의 중재를 통해 해당 운동시설로부터 \r\n");
      out.write("    고객님의 환불이 정상적으로 이루어질 수 있도록 도와드립니다.\r\n");
      out.write("    <br><br>\r\n");
      out.write("    만약, 운동시설의 폐업 후 도주 등으로 인해\r\n");
      out.write("    정상적인 의사소통이 어려운 경우 \r\n");
      out.write("    <br>\r\n");
      out.write("    빠짐이 그동안 이용한 기간에 해당하는 금액을 공제하고 \r\n");
      out.write("    별도의 위약금(10%)없이 환불해 드립니다.\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"q-div\">\r\n");
      out.write("<h3>Q. QR 출석이 되지 않을 땐 어떻게 해야하나요?</h3>\r\n");
      out.write("\r\n");
      out.write("<div class=\"a-div\">\r\n");
      out.write("A.  해당 운동시설에 비치된 QR코드의 바코드 상태가 \r\n");
      out.write("    낡거나 훼손된 경우, QR인식이 어려운 경우가 있습니다.\r\n");
      out.write("    <br> \r\n");
      out.write("    이 경우 고객센테로 알려주시면 \r\n");
      out.write("    당일 방문건에 대해 출석처리를 도와드리고, \r\n");
      out.write("    해당 시설에는 새로운 QR 바코드를 다시 발송하겠습니다.\r\n");
      out.write("</div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"q-div\">\r\n");
      out.write("<h3>Q. QR출석을 깜빡하고 하지 못했어요.</h3>\r\n");
      out.write("\r\n");
      out.write("<div class=\"a-div\">\r\n");
      out.write("A.  통합회원권 고객님이 정상적으로 서비스를 이용하기 위해서는 \r\n");
      out.write("    <b>반드시 QR출석</b>이 필요합니다.\r\n");
      out.write("    <br>\r\n");
      out.write("    출석 할때마다 현금처럼 사용할 수 있는 <b>포인트가 지급</b>되며,\r\n");
      out.write("    고객님의 <b>운동기록도 편리하게 관리</b>가 가능하기 때문에 \r\n");
      out.write("    <br>\r\n");
      out.write("    반드시 방문할 때마다 출석체크를 진행해주세요!<br>\r\n");
      out.write("\r\n");
      out.write("    다만, 부득이한 사정으로 출석체크를 진행하지 못한 경우 \r\n");
      out.write("    당일 방문건에 대해 고객센터에서 출석처리를 도와드리겠습니다.\r\n");
      out.write("    <br>\r\n");
      out.write("    <br>\r\n");
      out.write("</div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
