/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.79
 * Generated at: 2023-08-24 10:37:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class gymList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    <!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>운동시설 상세 페이지</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/gymList.css\"/>\r\n");
      out.write("    <link rel=\"icon\" href=\"../img/로고.png\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"gym-list-container\"> <!-- 10개의 컨텐츠를 포괄하는 컨테이너 -->\r\n");
      out.write("            <div class=\"list-box\"> <!--가로로 두개의 컨텐츠를 묶음-->\r\n");
      out.write("              \r\n");
      out.write("                <div class=\"list-content\">\r\n");
      out.write("                        <div class=\"list-img-box\"><!--게시판 사진 컨테이너-->\r\n");
      out.write("                            <a href=\"../cuj/gymDetaile.html\">\r\n");
      out.write("                                <img class=\"list-img\" src=\"img-ljm/운동시설1.jpg\"/><!--게시판 사진-->\r\n");
      out.write("                            </a>\r\n");
      out.write("                            \r\n");
      out.write("                        </div>\r\n");
      out.write("                 \r\n");
      out.write("                    <div class=\"list-info\"> <!--게시판의 정보(텍스트)-->\r\n");
      out.write("                        <p class=\"gym-title\">묵동 바디캠프</p>\r\n");
      out.write("                        <p class=\"gym-address\">서울 중랑구 묵동</p>\r\n");
      out.write("                        <br>\r\n");
      out.write("                        \r\n");
      out.write("                      \r\n");
      out.write("                        <div class=\"gym-category-box-sort\">\r\n");
      out.write("                            <div class=\"gym-category-box\">\r\n");
      out.write("                                <div class=\"gym-category\">P.T</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"gym-category-box\">\r\n");
      out.write("                                <div class=\"gym-category\">수영</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("               \r\n");
      out.write("                \r\n");
      out.write("                    <div class=\"list-content\">\r\n");
      out.write("                        \r\n");
      out.write("                            <div class=\"list-img-box\"><!--게시판 사진 컨테이너-->\r\n");
      out.write("                                <a href=\"../cuj/gymDetaile.html\">\r\n");
      out.write("                                    <img class=\"list-img\" src=\"img-ljm/운동시설2.jpg\"/><!--게시판 사진-->\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                       \r\n");
      out.write("                       \r\n");
      out.write("                        <div class=\"list-info\"> <!--게시판의 정보(텍스트)-->\r\n");
      out.write("                            <p class=\"gym-title\">을지로 크로스핏 </p>\r\n");
      out.write("                            <p class=\"gym-address\">서울 중구 수표동</p>\r\n");
      out.write("                            <br>\r\n");
      out.write("                           \r\n");
      out.write("                            \r\n");
      out.write("                           \r\n");
      out.write("                            <div class=\"gym-category-box-sort\">\r\n");
      out.write("                                <div class=\"gym-category-box\">\r\n");
      out.write("                                    <div class=\"gym-category\">P.T</div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"list-box\"> <!--가로로 두개의 컨텐츠를 묶음-->\r\n");
      out.write("                <div class=\"list-content\">\r\n");
      out.write("                    \r\n");
      out.write("                        <div class=\"list-img-box\"><!--게시판 사진 컨테이너-->\r\n");
      out.write("                            <a href=\"../cuj/gymDetaile.html\">\r\n");
      out.write("                                <img class=\"list-img\" src=\"img-ljm/운동시설3.jpg\"/><!--게시판 사진-->\r\n");
      out.write("                            </a>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"list-info\"> <!--게시판의 정보(텍스트)-->\r\n");
      out.write("                        <p class=\"gym-title\">종로 스포짐</p>\r\n");
      out.write("                        <p class=\"gym-address\">서울 종로구 서린동</p>\r\n");
      out.write("                        <br>\r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"gym-category-box-sort\">\r\n");
      out.write("                            <div class=\"gym-category-box\">\r\n");
      out.write("                                <div class=\"gym-category\">P.T</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"gym-category-box\">\r\n");
      out.write("                                <div class=\"gym-category\">요가</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"list-content\">\r\n");
      out.write("                    \r\n");
      out.write("                        <div class=\"list-img-box\"><!--게시판 사진 컨테이너-->\r\n");
      out.write("                            <a href=\"../cuj/gymDetaile.html\">\r\n");
      out.write("                                <img class=\"list-img\" src=\"img-ljm/운동시설4.jpg\"/><!--게시판 사진-->\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"list-info\"> <!--게시판의 정보(텍스트)-->\r\n");
      out.write("                        <p class=\"gym-title\">시청 스포짐</p>\r\n");
      out.write("                        <p class=\"gym-address\">서울 중구 태평로2가</p>\r\n");
      out.write("                        <br>\r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"gym-category-box-sort\">\r\n");
      out.write("                            <div class=\"gym-category-box\">\r\n");
      out.write("                                <div class=\"gym-category\">P.T</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"list-box\"> <!--가로로 두개의 컨텐츠를 묶음-->\r\n");
      out.write("                <div class=\"list-content\">\r\n");
      out.write("                    \r\n");
      out.write("                        <div class=\"list-img-box\"><!--게시판 사진 컨테이너-->\r\n");
      out.write("                            <a href=\"../cuj/gymDetaile.html\">\r\n");
      out.write("                                <img class=\"list-img\" src=\"img-ljm/운동시설5.jpg\"/><!--게시판 사진-->\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"list-info\"> <!--게시판의 정보(텍스트)-->\r\n");
      out.write("                        <p class=\"gym-title\">광화문 피트니스</p>\r\n");
      out.write("                        <p class=\"gym-address\">서울 종로구 내수동</p>\r\n");
      out.write("                        <br>\r\n");
      out.write("            \r\n");
      out.write("                        <div class=\"gym-category-box-sort\">\r\n");
      out.write("                            <div class=\"gym-category-box\">\r\n");
      out.write("                                <div class=\"gym-category\">P.T</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"gym-category-box\">\r\n");
      out.write("                                <div class=\"gym-category\">골프</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"list-content\">\r\n");
      out.write("                    \r\n");
      out.write("                        <div class=\"list-img-box\"><!--게시판 사진 컨테이너-->\r\n");
      out.write("                            <a href=\"../cuj/gymDetaile.html\">\r\n");
      out.write("                                <img class=\"list-img\" src=\"img-ljm/운동시설6.jpg\"/><!--게시판 사진-->\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                   \r\n");
      out.write("                    <div class=\"list-info\"> <!--게시판의 정보(텍스트)-->\r\n");
      out.write("                        <p class=\"gym-title\">신당 관리의기술</p>\r\n");
      out.write("                        <p class=\"gym-address\">서울 중구 흥인동</p>\r\n");
      out.write("                        <br>\r\n");
      out.write("                       \r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"gym-category-box-sort\">\r\n");
      out.write("                            <div class=\"gym-category-box\">\r\n");
      out.write("                                <div class=\"gym-category\">P.T</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"list-box\"> <!--가로로 두개의 컨텐츠를 묶음-->\r\n");
      out.write("                <div class=\"list-content\">\r\n");
      out.write("                    \r\n");
      out.write("                        <div class=\"list-img-box\"><!--게시판 사진 컨테이너-->\r\n");
      out.write("                            <a href=\"../cuj/gymDetaile.html\">\r\n");
      out.write("                                <img class=\"list-img\" src=\"img-ljm/운동시설7.jpg\"/><!--게시판 사진-->\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"list-info\"> <!--게시판의 정보(텍스트)-->\r\n");
      out.write("                        <p class=\"gym-title\">숙대입구 망고짐</p>\r\n");
      out.write("                        <p class=\"gym-address\">서울 용산구 남영동</p>\r\n");
      out.write("                        <br>\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"gym-category-box-sort\">\r\n");
      out.write("                            <div class=\"gym-category-box\">\r\n");
      out.write("                                <div class=\"gym-category\">P.T</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"gym-category-box\">\r\n");
      out.write("                                <div class=\"gym-category\">복싱</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"list-content\">\r\n");
      out.write("                    \r\n");
      out.write("                        <div class=\"list-img-box\"><!--게시판 사진 컨테이너-->\r\n");
      out.write("                           <a href=\"../cuj/gymDetaile.html\">\r\n");
      out.write("                            <img class=\"list-img\" src=\"img-ljm/운동시설8.jpg\"/><!--게시판 사진-->\r\n");
      out.write("                           </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"list-info\"> <!--게시판의 정보(텍스트)-->\r\n");
      out.write("                        <p class=\"gym-title\">애오개 헬스존</p>\r\n");
      out.write("                        <p class=\"gym-address\">서울 마포구 공덕동</p>\r\n");
      out.write("                        <br>\r\n");
      out.write("                     \r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"gym-category-box-sort\">\r\n");
      out.write("                            <div class=\"gym-category-box\">\r\n");
      out.write("                                <div class=\"gym-category\">P.T</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"list-box\"> <!--가로로 두개의 컨텐츠를 묶음-->\r\n");
      out.write("                <div class=\"list-content\">\r\n");
      out.write("                    \r\n");
      out.write("                        <div class=\"list-img-box\"><!--게시판 사진 컨테이너-->\r\n");
      out.write("                            <a href=\"../cuj/gymDetaile.html\">\r\n");
      out.write("                                <img class=\"list-img\" src=\"img-ljm/운동시설9.jpg\"/><!--게시판 사진-->\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                   \r\n");
      out.write("                    <div class=\"list-info\"> <!--게시판의 정보(텍스트)-->\r\n");
      out.write("                        <p class=\"gym-title\">공덕 킬러바디짐</p>\r\n");
      out.write("                        <p class=\"gym-address\">서울 마포구 공덕동</p>\r\n");
      out.write("                        <br>\r\n");
      out.write("                       \r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"gym-category-box-sort\">\r\n");
      out.write("                            <div class=\"gym-category-box\">\r\n");
      out.write("                                <div class=\"gym-category\">P.T</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"list-content\">\r\n");
      out.write("                    \r\n");
      out.write("                        <div class=\"list-img-box\"><!--게시판 사진 컨테이너-->\r\n");
      out.write("                            <a href=\"../cuj/gymDetaile.html\">\r\n");
      out.write("                                <img class=\"list-img\" src=\"img-ljm/운동시설10.jpg\"/><!--게시판 사진-->\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"list-info\"> <!--게시판의 정보(텍스트)-->\r\n");
      out.write("                        <p class=\"gym-title\">왕십리 릴리브짐</p>\r\n");
      out.write("                        <p class=\"gym-address\">서울 성동구 하왕십리동</p>\r\n");
      out.write("                        <br>\r\n");
      out.write("                       \r\n");
      out.write("                       \r\n");
      out.write("                        <div class=\"gym-category-box-sort\">\r\n");
      out.write("                            <div class=\"gym-category-box\">\r\n");
      out.write("                                <div class=\"gym-category\">P.T</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"gym-category-box\">\r\n");
      out.write("                                <div class=\"gym-category\">헬스</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"gym-category-box\">\r\n");
      out.write("                                <div class=\"gym-category\">필라</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"input-form\">\r\n");
      out.write("            <button class=\"write-button\" onclick=\"location.href='../cuj/gymWrite.html'\" >글작성</button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
