/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.79
 * Generated at: 2023-08-24 10:42:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class noticeDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    <!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>공지사항 상세페이지</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/noticeDetail.css\"/>\r\n");
      out.write("    <link rel=\"icon\" href=\"../img/로고.png\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"title\"> <!--제목이 들어가는 부분-->\r\n");
      out.write("            <h2>3차 코로나19 관련 홀딩 추가 공지</h2>\r\n");
      out.write("        </div>\r\n");
      out.write("       \r\n");
      out.write("        <div class=\"content-container\"> <!--내용이 들어가는 부분-->\r\n");
      out.write("            <div class=\"content\">\r\n");
      out.write("                <pre class=\"content-area\" >\r\n");
      out.write("안녕하세요.\r\n");
      out.write("운동할 땐, 다짐부터! 다짐입니다.\r\n");
      out.write("                    \r\n");
      out.write("최근 사회적 거리두기 2.5단계 격상으로 인해 일부 제휴 시설들의 운영이  12월 28일까지 중단됩니다.\r\n");
      out.write("따라서 모든 통합회원권 고객님들 대상으로,요청 고객님께 한하여 추가 홀딩을 제공드립니다.\r\n");
      out.write("                    \r\n");
      out.write("[기존]\r\n");
      out.write("[단일회원권]\r\n");
      out.write("- 결제하신 운동시설에 문의\r\n");
      out.write("                    \r\n");
      out.write("[통합회원권]\r\n");
      out.write("- 다짐 앱 내에서 신청 (3개월 2주 / 6개월 4주 / 12개월 8주)\r\n");
      out.write("                    \r\n");
      out.write("[변경]\r\n");
      out.write("[단일회원권]\r\n");
      out.write("- 결제하신 운동시설에 문의 (대부분의 다짐제휴운동시설에서도 홀딩을 넉넉하게 적용하고 있습니다)\r\n");
      out.write("                    \r\n");
      out.write("[통합회원권]\r\n");
      out.write("- 기존 규정(3개월 2주 / 6개월 4주 / 12개월 8주)과 별개로 채팅상담 문의시 1회에 한하여 한달 홀딩 연장\r\n");
      out.write("                    \r\n");
      out.write("[신청방법]\r\n");
      out.write("[마이다짐] - [채팅상담(우측 하단의 말풍선 아이콘)] - [회원권 이용 및 출석문의] - [[코로나19] 홀딩 신청]\r\n");
      out.write("*채팅상담 버튼이 안보이면, 앱을 최신 버전으로 업데이트 후 이용해주세요!\r\n");
      out.write("                    \r\n");
      out.write("마음 편히 운동할 수 있는 일상을 되찾고자 회원님들과 함께 노력하는 다짐이 되겠습니다.\r\n");
      out.write("                    \r\n");
      out.write("감사합니다.\r\n");
      out.write("다짐 드림            \r\n");
      out.write("                </pre>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"btn-container\">\r\n");
      out.write("            <button type=\"submit\" value=\"수정\" id=\"update\" onclick=\"location.href='../cuj/noticeWrite.html'\">수정</button>\r\n");
      out.write("            <button type=\"submit\" value=\"삭제\" id=\"delete\" onclick=\"confirm('정말 삭제하시겠습니까?')\">삭제</button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
